
package com.brandmaker.soap.jobmanager;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DsePortTypeV2", targetNamespace = "http://brandmaker.com/webservices/dse/v2/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DsePortTypeV2 {


    /**
     * 
     * @param technicalNames
     * @param id
     * @param localeId
     * @return
     *     returns com.brandmaker.soap.jobmanager.DetailedList
     */
    @WebMethod
    @WebResult(targetNamespace = "http://brandmaker.com/webservices/dse/v2/")
    @RequestWrapper(localName = "findVariablesByTechnicalNames", targetNamespace = "http://brandmaker.com/webservices/dse/v2/", className = "com.brandmaker.soap.jobmanager.FindVariablesByTechnicalNames")
    @ResponseWrapper(localName = "findVariablesByTechnicalNamesResponse", targetNamespace = "http://brandmaker.com/webservices/dse/v2/", className = "com.brandmaker.soap.jobmanager.FindVariablesByTechnicalNamesResponse")
    public DetailedList findVariablesByTechnicalNames(
        @WebParam(name = "id", targetNamespace = "")
        Integer id,
        @WebParam(name = "localeId", targetNamespace = "")
        Integer localeId,
        @WebParam(name = "technicalNames", targetNamespace = "")
        List<String> technicalNames);

    /**
     * 
     * @param technicalName
     * @return
     *     returns com.brandmaker.soap.jobmanager.VariableTypeList
     * @throws InternalServerFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findVariableTypes", targetNamespace = "http://brandmaker.com/webservices/dse/v2/", className = "com.brandmaker.soap.jobmanager.FindVariableTypes")
    @ResponseWrapper(localName = "findVariableTypesResponse", targetNamespace = "http://brandmaker.com/webservices/dse/v2/", className = "com.brandmaker.soap.jobmanager.FindVariableTypesResponse")
    public VariableTypeList findVariableTypes(
        @WebParam(name = "technicalName", targetNamespace = "")
        String technicalName)
        throws InternalServerFault_Exception
    ;

    /**
     * 
     * @param newLocaleId
     * @param id
     * @param newObjectName
     * @param workflowTypeName
     * @return
     *     returns com.brandmaker.soap.jobmanager.Result
     * @throws InternalServerFault_Exception
     * @throws DseWebServiceFault_Exception
     * @throws DseObjectNotFoundFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "http://brandmaker.com/webservices/dse/v2/")
    @RequestWrapper(localName = "addDseObjectLocale", targetNamespace = "http://brandmaker.com/webservices/dse/v2/", className = "com.brandmaker.soap.jobmanager.AddDseObjectLocale")
    @ResponseWrapper(localName = "addDseObjectLocaleResponse", targetNamespace = "http://brandmaker.com/webservices/dse/v2/", className = "com.brandmaker.soap.jobmanager.AddDseObjectLocaleResponse")
    public Result addDseObjectLocale(
        @WebParam(name = "id", targetNamespace = "")
        Integer id,
        @WebParam(name = "newObjectName", targetNamespace = "")
        String newObjectName,
        @WebParam(name = "newLocaleId", targetNamespace = "")
        Integer newLocaleId,
        @WebParam(name = "workflowTypeName", targetNamespace = "")
        String workflowTypeName)
        throws DseObjectNotFoundFault_Exception, DseWebServiceFault_Exception, InternalServerFault_Exception
    ;

    /**
     * 
     * @param dseObjectId
     * @param editable
     * @param variableTypeId
     * @param value
     * @param localeId
     * @return
     *     returns com.brandmaker.soap.jobmanager.Result
     */
    @WebMethod
    @WebResult(targetNamespace = "http://brandmaker.com/webservices/dse/v2/")
    @RequestWrapper(localName = "updateVariable", targetNamespace = "http://brandmaker.com/webservices/dse/v2/", className = "com.brandmaker.soap.jobmanager.UpdateVariable")
    @ResponseWrapper(localName = "updateVariableResponse", targetNamespace = "http://brandmaker.com/webservices/dse/v2/", className = "com.brandmaker.soap.jobmanager.UpdateVariableResponse")
    public Result updateVariable(
        @WebParam(name = "variableTypeId", targetNamespace = "")
        Integer variableTypeId,
        @WebParam(name = "dseObjectId", targetNamespace = "")
        Integer dseObjectId,
        @WebParam(name = "localeId", targetNamespace = "")
        Integer localeId,
        @WebParam(name = "editable", targetNamespace = "")
        Boolean editable,
        @WebParam(name = "value", targetNamespace = "")
        String value);

    /**
     * 
     * @param dseModule
     * @return
     *     returns com.brandmaker.soap.jobmanager.DseObjectTypeList
     * @throws InternalServerFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findDseObjectTypes", targetNamespace = "http://brandmaker.com/webservices/dse/v2/", className = "com.brandmaker.soap.jobmanager.FindDseObjectTypes")
    @ResponseWrapper(localName = "findDseObjectTypesResponse", targetNamespace = "http://brandmaker.com/webservices/dse/v2/", className = "com.brandmaker.soap.jobmanager.FindDseObjectTypesResponse")
    public DseObjectTypeList findDseObjectTypes(
        @WebParam(name = "dseModule", targetNamespace = "")
        DseModule dseModule)
        throws InternalServerFault_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns com.brandmaker.soap.jobmanager.CustomStructureList
     */
    @WebMethod
    @WebResult(targetNamespace = "http://brandmaker.com/webservices/dse/v2/")
    @RequestWrapper(localName = "findAllCustomStructures", targetNamespace = "http://brandmaker.com/webservices/dse/v2/", className = "com.brandmaker.soap.jobmanager.FindAllCustomStructures")
    @ResponseWrapper(localName = "findAllCustomStructuresResponse", targetNamespace = "http://brandmaker.com/webservices/dse/v2/", className = "com.brandmaker.soap.jobmanager.FindAllCustomStructuresResponse")
    public CustomStructureList findAllCustomStructures(
        @WebParam(name = "arg0", targetNamespace = "")
        List<String> arg0);

    /**
     * 
     * @param l10NLocaleId
     * @param dseInstanceId
     * @return
     *     returns com.brandmaker.soap.jobmanager.WorkflowStepAssignmentDto
     * @throws InternalServerFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "http://brandmaker.com/webservices/dse/v2/")
    @RequestWrapper(localName = "getForwardCandidates", targetNamespace = "http://brandmaker.com/webservices/dse/v2/", className = "com.brandmaker.soap.jobmanager.GetForwardCandidates")
    @ResponseWrapper(localName = "getForwardCandidatesResponse", targetNamespace = "http://brandmaker.com/webservices/dse/v2/", className = "com.brandmaker.soap.jobmanager.GetForwardCandidatesResponse")
    public WorkflowStepAssignmentDto getForwardCandidates(
        @WebParam(name = "dseInstanceId", targetNamespace = "")
        Integer dseInstanceId,
        @WebParam(name = "l10nLocaleId", targetNamespace = "")
        Integer l10NLocaleId)
        throws InternalServerFault_Exception
    ;

    /**
     * 
     * @param initiationUser
     * @param assignees
     * @param dseInstanceId
     * @param comment
     * @param localeId
     * @return
     *     returns com.brandmaker.soap.jobmanager.Result
     * @throws InternalServerFault_Exception
     * @throws UserNotFoundFault_Exception
     * @throws InvalidAssigneeFault_Exception
     * @throws AreaNotFoundFault_Exception
     * @throws DseObjectNotFoundFault_Exception
     * @throws DuplicateAreaFault_Exception
     * @throws InvalidDseObjectFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "forwardDseObject", targetNamespace = "http://brandmaker.com/webservices/dse/v2/", className = "com.brandmaker.soap.jobmanager.ForwardDseObject")
    @ResponseWrapper(localName = "forwardDseObjectResponse", targetNamespace = "http://brandmaker.com/webservices/dse/v2/", className = "com.brandmaker.soap.jobmanager.ForwardDseObjectResponse")
    public Result forwardDseObject(
        @WebParam(name = "initiationUser", targetNamespace = "")
        String initiationUser,
        @WebParam(name = "dseInstanceId", targetNamespace = "")
        Integer dseInstanceId,
        @WebParam(name = "localeId", targetNamespace = "")
        Integer localeId,
        @WebParam(name = "assignees", targetNamespace = "")
        List<AssigneeDto> assignees,
        @WebParam(name = "comment", targetNamespace = "")
        String comment)
        throws AreaNotFoundFault_Exception, DseObjectNotFoundFault_Exception, DuplicateAreaFault_Exception, InternalServerFault_Exception, InvalidAssigneeFault_Exception, InvalidDseObjectFault_Exception, UserNotFoundFault_Exception
    ;

    /**
     * 
     * @param data
     * @return
     *     returns com.brandmaker.soap.jobmanager.Result
     */
    @WebMethod
    @WebResult(targetNamespace = "http://brandmaker.com/webservices/dse/v2/")
    @RequestWrapper(localName = "create", targetNamespace = "http://brandmaker.com/webservices/dse/v2/", className = "com.brandmaker.soap.jobmanager.Create")
    @ResponseWrapper(localName = "createResponse", targetNamespace = "http://brandmaker.com/webservices/dse/v2/", className = "com.brandmaker.soap.jobmanager.CreateResponse")
    public Result create(
        @WebParam(name = "data", targetNamespace = "http://brandmaker.com/webservices/dse/v2/")
        DescriptionDto data);

    /**
     * 
     * @param data
     * @return
     *     returns com.brandmaker.soap.jobmanager.Result
     */
    @WebMethod
    @WebResult(targetNamespace = "http://brandmaker.com/webservices/dse/v2/")
    @RequestWrapper(localName = "createV2", targetNamespace = "http://brandmaker.com/webservices/dse/v2/", className = "com.brandmaker.soap.jobmanager.CreateV2")
    @ResponseWrapper(localName = "createV2Response", targetNamespace = "http://brandmaker.com/webservices/dse/v2/", className = "com.brandmaker.soap.jobmanager.CreateV2Response")
    public Result createV2(
        @WebParam(name = "data", targetNamespace = "http://brandmaker.com/webservices/dse/v2/")
        DescriptionDto data);

    /**
     * 
     * @return
     *     returns com.brandmaker.soap.jobmanager.Result
     */
    @WebMethod
    @WebResult(targetNamespace = "http://brandmaker.com/webservices/dse/v2/")
    @RequestWrapper(localName = "updateDseSchemaFrom15To20", targetNamespace = "http://brandmaker.com/webservices/dse/v2/", className = "com.brandmaker.soap.jobmanager.UpdateDseSchemaFrom15To20")
    @ResponseWrapper(localName = "updateDseSchemaFrom15To20Response", targetNamespace = "http://brandmaker.com/webservices/dse/v2/", className = "com.brandmaker.soap.jobmanager.UpdateDseSchemaFrom15To20Response")
    public Result updateDseSchemaFrom15To20();

    /**
     * 
     * @param id
     * @param localeId
     * @return
     *     returns com.brandmaker.soap.jobmanager.DetailedList
     */
    @WebMethod
    @WebResult(targetNamespace = "http://brandmaker.com/webservices/dse/v2/")
    @RequestWrapper(localName = "findById", targetNamespace = "http://brandmaker.com/webservices/dse/v2/", className = "com.brandmaker.soap.jobmanager.FindById")
    @ResponseWrapper(localName = "findByIdResponse", targetNamespace = "http://brandmaker.com/webservices/dse/v2/", className = "com.brandmaker.soap.jobmanager.FindByIdResponse")
    public DetailedList findById(
        @WebParam(name = "id", targetNamespace = "")
        Integer id,
        @WebParam(name = "localeId", targetNamespace = "")
        List<Integer> localeId);

    /**
     * 
     * @param dseInstanceId
     * @return
     *     returns com.brandmaker.soap.jobmanager.LocalesResult
     * @throws InternalServerFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findLocalesOfDseObject", targetNamespace = "http://brandmaker.com/webservices/dse/v2/", className = "com.brandmaker.soap.jobmanager.FindLocalesOfDseObject")
    @ResponseWrapper(localName = "findLocalesOfDseObjectResponse", targetNamespace = "http://brandmaker.com/webservices/dse/v2/", className = "com.brandmaker.soap.jobmanager.FindLocalesOfDseObjectResponse")
    public LocalesResult findLocalesOfDseObject(
        @WebParam(name = "dseInstanceId", targetNamespace = "")
        Integer dseInstanceId)
        throws InternalServerFault_Exception
    ;

    /**
     * 
     * @param filter
     * @return
     *     returns com.brandmaker.soap.jobmanager.Result
     */
    @WebMethod
    @WebResult(targetNamespace = "http://brandmaker.com/webservices/dse/v2/")
    @RequestWrapper(localName = "findByFilterUnique", targetNamespace = "http://brandmaker.com/webservices/dse/v2/", className = "com.brandmaker.soap.jobmanager.FindByFilterUnique")
    @ResponseWrapper(localName = "findByFilterUniqueResponse", targetNamespace = "http://brandmaker.com/webservices/dse/v2/", className = "com.brandmaker.soap.jobmanager.FindByFilterUniqueResponse")
    public Result findByFilterUnique(
        @WebParam(name = "filter", targetNamespace = "http://brandmaker.com/webservices/dse/v2/")
        FilterDto filter);

    /**
     * 
     * @param limitToRootLevel
     * @param start
     * @param limit
     * @param localeId
     * @return
     *     returns com.brandmaker.soap.jobmanager.DetailedList
     */
    @WebMethod
    @WebResult(targetNamespace = "http://brandmaker.com/webservices/dse/v2/")
    @RequestWrapper(localName = "findAllProducts", targetNamespace = "http://brandmaker.com/webservices/dse/v2/", className = "com.brandmaker.soap.jobmanager.FindAllProducts")
    @ResponseWrapper(localName = "findAllProductsResponse", targetNamespace = "http://brandmaker.com/webservices/dse/v2/", className = "com.brandmaker.soap.jobmanager.FindAllProductsResponse")
    public DetailedList findAllProducts(
        @WebParam(name = "limitToRootLevel", targetNamespace = "")
        boolean limitToRootLevel,
        @WebParam(name = "localeId", targetNamespace = "")
        List<Integer> localeId,
        @WebParam(name = "start", targetNamespace = "")
        Integer start,
        @WebParam(name = "limit", targetNamespace = "")
        Integer limit);

    /**
     * 
     * @param l10NLocaleId
     * @param dseInstanceId
     * @return
     *     returns com.brandmaker.soap.jobmanager.WorkflowStepAssignmentDto
     * @throws InternalServerFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "http://brandmaker.com/webservices/dse/v2/")
    @RequestWrapper(localName = "getRejectCandidates", targetNamespace = "http://brandmaker.com/webservices/dse/v2/", className = "com.brandmaker.soap.jobmanager.GetRejectCandidates")
    @ResponseWrapper(localName = "getRejectCandidatesResponse", targetNamespace = "http://brandmaker.com/webservices/dse/v2/", className = "com.brandmaker.soap.jobmanager.GetRejectCandidatesResponse")
    public WorkflowStepAssignmentDto getRejectCandidates(
        @WebParam(name = "dseInstanceId", targetNamespace = "")
        Integer dseInstanceId,
        @WebParam(name = "l10nLocaleId", targetNamespace = "")
        Integer l10NLocaleId)
        throws InternalServerFault_Exception
    ;

    /**
     * 
     * @param filterId
     * @param start
     * @param limit
     * @param topicName
     * @param localeId
     * @return
     *     returns com.brandmaker.soap.jobmanager.DetailedList
     */
    @WebMethod
    @WebResult(targetNamespace = "http://brandmaker.com/webservices/dse/v2/")
    @RequestWrapper(localName = "findByFilterId", targetNamespace = "http://brandmaker.com/webservices/dse/v2/", className = "com.brandmaker.soap.jobmanager.FindByFilterId")
    @ResponseWrapper(localName = "findByFilterIdResponse", targetNamespace = "http://brandmaker.com/webservices/dse/v2/", className = "com.brandmaker.soap.jobmanager.FindByFilterIdResponse")
    public DetailedList findByFilterId(
        @WebParam(name = "filterId", targetNamespace = "")
        Integer filterId,
        @WebParam(name = "topicName", targetNamespace = "")
        String topicName,
        @WebParam(name = "start", targetNamespace = "")
        Integer start,
        @WebParam(name = "limit", targetNamespace = "")
        Integer limit,
        @WebParam(name = "localeId", targetNamespace = "")
        List<Integer> localeId);

    /**
     * 
     * @param includeSubJobs
     * @param start
     * @param limit
     * @return
     *     returns com.brandmaker.soap.jobmanager.DetailedList
     */
    @WebMethod
    @WebResult(targetNamespace = "http://brandmaker.com/webservices/dse/v2/")
    @RequestWrapper(localName = "findAllJobs", targetNamespace = "http://brandmaker.com/webservices/dse/v2/", className = "com.brandmaker.soap.jobmanager.FindAllJobs")
    @ResponseWrapper(localName = "findAllJobsResponse", targetNamespace = "http://brandmaker.com/webservices/dse/v2/", className = "com.brandmaker.soap.jobmanager.FindAllJobsResponse")
    public DetailedList findAllJobs(
        @WebParam(name = "includeSubJobs", targetNamespace = "")
        boolean includeSubJobs,
        @WebParam(name = "start", targetNamespace = "")
        Integer start,
        @WebParam(name = "limit", targetNamespace = "")
        Integer limit);

    /**
     * 
     * @param id
     * @param localeId
     * @return
     *     returns com.brandmaker.soap.jobmanager.VariableHistoryResult
     */
    @WebMethod
    @WebResult(targetNamespace = "http://brandmaker.com/webservices/dse/v2/")
    @RequestWrapper(localName = "getLastChangesById", targetNamespace = "http://brandmaker.com/webservices/dse/v2/", className = "com.brandmaker.soap.jobmanager.GetLastChangesById")
    @ResponseWrapper(localName = "getLastChangesByIdResponse", targetNamespace = "http://brandmaker.com/webservices/dse/v2/", className = "com.brandmaker.soap.jobmanager.GetLastChangesByIdResponse")
    public VariableHistoryResult getLastChangesById(
        @WebParam(name = "id", targetNamespace = "")
        Integer id,
        @WebParam(name = "localeId", targetNamespace = "")
        Integer localeId);

    /**
     * 
     * @param data
     * @return
     *     returns com.brandmaker.soap.jobmanager.Result
     */
    @WebMethod
    @WebResult(targetNamespace = "http://brandmaker.com/webservices/dse/v2/")
    @RequestWrapper(localName = "updateById", targetNamespace = "http://brandmaker.com/webservices/dse/v2/", className = "com.brandmaker.soap.jobmanager.UpdateById")
    @ResponseWrapper(localName = "updateByIdResponse", targetNamespace = "http://brandmaker.com/webservices/dse/v2/", className = "com.brandmaker.soap.jobmanager.UpdateByIdResponse")
    public Result updateById(
        @WebParam(name = "data", targetNamespace = "http://brandmaker.com/webservices/dse/v2/")
        DescriptionDto data);

    /**
     * 
     * @param ids
     * @param localeId
     * @return
     *     returns com.brandmaker.soap.jobmanager.DetailedList
     */
    @WebMethod
    @WebResult(targetNamespace = "http://brandmaker.com/webservices/dse/v2/")
    @RequestWrapper(localName = "findByIds", targetNamespace = "http://brandmaker.com/webservices/dse/v2/", className = "com.brandmaker.soap.jobmanager.FindByIds")
    @ResponseWrapper(localName = "findByIdsResponse", targetNamespace = "http://brandmaker.com/webservices/dse/v2/", className = "com.brandmaker.soap.jobmanager.FindByIdsResponse")
    public DetailedList findByIds(
        @WebParam(name = "ids", targetNamespace = "")
        List<Integer> ids,
        @WebParam(name = "localeId", targetNamespace = "")
        List<Integer> localeId);

    /**
     * 
     * @param initiationUser
     * @param assignees
     * @param dseInstanceId
     * @param comment
     * @param localeId
     * @return
     *     returns com.brandmaker.soap.jobmanager.Result
     * @throws InternalServerFault_Exception
     * @throws UserNotFoundFault_Exception
     * @throws InvalidAssigneeFault_Exception
     * @throws AreaNotFoundFault_Exception
     * @throws DuplicateAreaFault_Exception
     * @throws DseObjectNotFoundFault_Exception
     * @throws InvalidDseObjectFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "rejectDseObject", targetNamespace = "http://brandmaker.com/webservices/dse/v2/", className = "com.brandmaker.soap.jobmanager.RejectDseObject")
    @ResponseWrapper(localName = "rejectDseObjectResponse", targetNamespace = "http://brandmaker.com/webservices/dse/v2/", className = "com.brandmaker.soap.jobmanager.RejectDseObjectResponse")
    public Result rejectDseObject(
        @WebParam(name = "initiationUser", targetNamespace = "")
        String initiationUser,
        @WebParam(name = "dseInstanceId", targetNamespace = "")
        Integer dseInstanceId,
        @WebParam(name = "localeId", targetNamespace = "")
        Integer localeId,
        @WebParam(name = "assignees", targetNamespace = "")
        List<AssigneeDto> assignees,
        @WebParam(name = "comment", targetNamespace = "")
        String comment)
        throws AreaNotFoundFault_Exception, DseObjectNotFoundFault_Exception, DuplicateAreaFault_Exception, InternalServerFault_Exception, InvalidAssigneeFault_Exception, InvalidDseObjectFault_Exception, UserNotFoundFault_Exception
    ;

    /**
     * 
     * @param orderId
     * @param dseModule
     * @param locale
     * @return
     *     returns com.brandmaker.soap.jobmanager.DetailedList
     */
    @WebMethod
    @WebResult(targetNamespace = "http://brandmaker.com/webservices/dse/v2/")
    @RequestWrapper(localName = "findByOrderId", targetNamespace = "http://brandmaker.com/webservices/dse/v2/", className = "com.brandmaker.soap.jobmanager.FindByOrderId")
    @ResponseWrapper(localName = "findByOrderIdResponse", targetNamespace = "http://brandmaker.com/webservices/dse/v2/", className = "com.brandmaker.soap.jobmanager.FindByOrderIdResponse")
    public DetailedList findByOrderId(
        @WebParam(name = "dseModule", targetNamespace = "")
        DseModule dseModule,
        @WebParam(name = "orderId", targetNamespace = "")
        Integer orderId,
        @WebParam(name = "locale", targetNamespace = "")
        Integer locale);

    /**
     * 
     * @param filter
     * @param searchTerm
     * @param includeSubJobs
     * @param localeId
     * @return
     *     returns com.brandmaker.soap.jobmanager.DetailedList
     */
    @WebMethod
    @WebResult(targetNamespace = "http://brandmaker.com/webservices/dse/v2/")
    @RequestWrapper(localName = "findByFilter", targetNamespace = "http://brandmaker.com/webservices/dse/v2/", className = "com.brandmaker.soap.jobmanager.FindByFilter")
    @ResponseWrapper(localName = "findByFilterResponse", targetNamespace = "http://brandmaker.com/webservices/dse/v2/", className = "com.brandmaker.soap.jobmanager.FindByFilterResponse")
    public DetailedList findByFilter(
        @WebParam(name = "filter", targetNamespace = "http://brandmaker.com/webservices/dse/v2/")
        FilterDto filter,
        @WebParam(name = "searchTerm", targetNamespace = "")
        List<String> searchTerm,
        @WebParam(name = "includeSubJobs", targetNamespace = "")
        boolean includeSubJobs,
        @WebParam(name = "localeId", targetNamespace = "")
        List<Integer> localeId);

    /**
     * 
     * @param instanceId
     * @param state
     * @param localeId
     * @return
     *     returns com.brandmaker.soap.jobmanager.Result
     */
    @WebMethod
    @WebResult(targetNamespace = "http://brandmaker.com/webservices/dse/v2/")
    @RequestWrapper(localName = "setState", targetNamespace = "http://brandmaker.com/webservices/dse/v2/", className = "com.brandmaker.soap.jobmanager.SetState")
    @ResponseWrapper(localName = "setStateResponse", targetNamespace = "http://brandmaker.com/webservices/dse/v2/", className = "com.brandmaker.soap.jobmanager.SetStateResponse")
    public Result setState(
        @WebParam(name = "instanceId", targetNamespace = "")
        Integer instanceId,
        @WebParam(name = "localeId", targetNamespace = "")
        Integer localeId,
        @WebParam(name = "state", targetNamespace = "http://brandmaker.com/webservices/dse/v2/")
        DseObjectState state);

    /**
     * 
     * @param dseObjectId
     * @param grid
     * @param gridVariableTypeId
     * @param localeId
     * @return
     *     returns com.brandmaker.soap.jobmanager.Result
     */
    @WebMethod
    @WebResult(targetNamespace = "http://brandmaker.com/webservices/dse/v2/")
    @RequestWrapper(localName = "updateGrid", targetNamespace = "http://brandmaker.com/webservices/dse/v2/", className = "com.brandmaker.soap.jobmanager.UpdateGrid")
    @ResponseWrapper(localName = "updateGridResponse", targetNamespace = "http://brandmaker.com/webservices/dse/v2/", className = "com.brandmaker.soap.jobmanager.UpdateGridResponse")
    public Result updateGrid(
        @WebParam(name = "gridVariableTypeId", targetNamespace = "")
        Integer gridVariableTypeId,
        @WebParam(name = "dseObjectId", targetNamespace = "")
        Integer dseObjectId,
        @WebParam(name = "localeId", targetNamespace = "")
        Integer localeId,
        @WebParam(name = "grid", targetNamespace = "http://brandmaker.com/webservices/dse/v2/")
        GridDto grid);

    /**
     * 
     * @return
     *     returns com.brandmaker.soap.jobmanager.LocalesResult
     * @throws InternalServerFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAllLocales", targetNamespace = "http://brandmaker.com/webservices/dse/v2/", className = "com.brandmaker.soap.jobmanager.FindAllLocales")
    @ResponseWrapper(localName = "findAllLocalesResponse", targetNamespace = "http://brandmaker.com/webservices/dse/v2/", className = "com.brandmaker.soap.jobmanager.FindAllLocalesResponse")
    public LocalesResult findAllLocales()
        throws InternalServerFault_Exception
    ;

    /**
     * 
     * @param typeNames
     * @param id
     * @param localeId
     * @return
     *     returns com.brandmaker.soap.jobmanager.DetailedList
     */
    @WebMethod
    @WebResult(targetNamespace = "http://brandmaker.com/webservices/dse/v2/")
    @RequestWrapper(localName = "findVariablesByType", targetNamespace = "http://brandmaker.com/webservices/dse/v2/", className = "com.brandmaker.soap.jobmanager.FindVariablesByType")
    @ResponseWrapper(localName = "findVariablesByTypeResponse", targetNamespace = "http://brandmaker.com/webservices/dse/v2/", className = "com.brandmaker.soap.jobmanager.FindVariablesByTypeResponse")
    public DetailedList findVariablesByType(
        @WebParam(name = "id", targetNamespace = "")
        Integer id,
        @WebParam(name = "localeId", targetNamespace = "")
        Integer localeId,
        @WebParam(name = "typeNames", targetNamespace = "")
        List<String> typeNames);

    /**
     * 
     * @param initiationUser
     * @param assignees
     * @param dseInstanceId
     * @param comment
     * @param localeId
     * @return
     *     returns com.brandmaker.soap.jobmanager.Result
     * @throws InternalServerFault_Exception
     * @throws UserNotFoundFault_Exception
     * @throws InvalidAssigneeFault_Exception
     * @throws AreaNotFoundFault_Exception
     * @throws DuplicateAreaFault_Exception
     * @throws DseObjectNotFoundFault_Exception
     * @throws InvalidDseObjectFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "changeAssignee", targetNamespace = "http://brandmaker.com/webservices/dse/v2/", className = "com.brandmaker.soap.jobmanager.ChangeAssignee")
    @ResponseWrapper(localName = "changeAssigneeResponse", targetNamespace = "http://brandmaker.com/webservices/dse/v2/", className = "com.brandmaker.soap.jobmanager.ChangeAssigneeResponse")
    public Result changeAssignee(
        @WebParam(name = "initiationUser", targetNamespace = "")
        String initiationUser,
        @WebParam(name = "dseInstanceId", targetNamespace = "")
        Integer dseInstanceId,
        @WebParam(name = "localeId", targetNamespace = "")
        Integer localeId,
        @WebParam(name = "assignees", targetNamespace = "")
        List<AssigneeDto> assignees,
        @WebParam(name = "comment", targetNamespace = "")
        String comment)
        throws AreaNotFoundFault_Exception, DseObjectNotFoundFault_Exception, DuplicateAreaFault_Exception, InternalServerFault_Exception, InvalidAssigneeFault_Exception, InvalidDseObjectFault_Exception, UserNotFoundFault_Exception
    ;

    /**
     * 
     * @param workflowTypeId
     * @return
     *     returns com.brandmaker.soap.jobmanager.WorkflowTypeResult
     * @throws InternalServerFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findWorkflowTypeById", targetNamespace = "http://brandmaker.com/webservices/dse/v2/", className = "com.brandmaker.soap.jobmanager.FindWorkflowTypeById")
    @ResponseWrapper(localName = "findWorkflowTypeByIdResponse", targetNamespace = "http://brandmaker.com/webservices/dse/v2/", className = "com.brandmaker.soap.jobmanager.FindWorkflowTypeByIdResponse")
    public WorkflowTypeResult findWorkflowTypeById(
        @WebParam(name = "workflowTypeId", targetNamespace = "")
        Integer workflowTypeId)
        throws InternalServerFault_Exception
    ;

    /**
     * 
     * @param topicName
     * @return
     *     returns com.brandmaker.soap.jobmanager.FiltersList
     */
    @WebMethod
    @WebResult(targetNamespace = "http://brandmaker.com/webservices/dse/v2/")
    @RequestWrapper(localName = "findAllFilter", targetNamespace = "http://brandmaker.com/webservices/dse/v2/", className = "com.brandmaker.soap.jobmanager.FindAllFilter")
    @ResponseWrapper(localName = "findAllFilterResponse", targetNamespace = "http://brandmaker.com/webservices/dse/v2/", className = "com.brandmaker.soap.jobmanager.FindAllFilterResponse")
    public FiltersList findAllFilter(
        @WebParam(name = "topicName", targetNamespace = "")
        String topicName);

    /**
     * 
     * @param technicalNameRelation
     * @param from
     * @param to
     * @param localeId
     * @return
     *     returns com.brandmaker.soap.jobmanager.Result
     */
    @WebMethod
    @WebResult(targetNamespace = "http://brandmaker.com/webservices/dse/v2/")
    @RequestWrapper(localName = "updateRelation", targetNamespace = "http://brandmaker.com/webservices/dse/v2/", className = "com.brandmaker.soap.jobmanager.UpdateRelation")
    @ResponseWrapper(localName = "updateRelationResponse", targetNamespace = "http://brandmaker.com/webservices/dse/v2/", className = "com.brandmaker.soap.jobmanager.UpdateRelationResponse")
    public Result updateRelation(
        @WebParam(name = "from", targetNamespace = "")
        Integer from,
        @WebParam(name = "technicalNameRelation", targetNamespace = "")
        String technicalNameRelation,
        @WebParam(name = "to", targetNamespace = "")
        Integer to,
        @WebParam(name = "localeId", targetNamespace = "")
        Integer localeId);

}
